### ISSUE TITLE
National Public Service Platform for Standards Information - China

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#291]
**你遇到了什么问题？** [必填]
- [x] 无法保存条目

**发生问题的链接** [必填]
[Testcast1](https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A)

**浏览器**
- [x] Chrome（谷歌浏览器）
- [x] FireFox（火狐浏览器）

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版

```shell
(3)(+0001289): translate message received in injected page https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/ping

(3)(+0000004): Connector: Method ping succeeded

(4)(+0000001): Translate: Binding sandbox to https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A

(3)(+0000001): progressWindow.show message received in injected page https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A

(4)(+0000004): Translate: Parsing code for National Public Service Platform for Standards Information - China (cd01cf63-90ba-42b4-a505-74d8d14f79d6, 2023-12-28 15:45:42)

(3)(+0000001): Translate: Beginning translation with National Public Service Platform for Standards Information - China

(1)(+0000000): {}

(2)(+0000001): Translate: Translation using National Public Service Platform for Standards Information - China failed: 
ReferenceError: cells is not defined

ReferenceError: cells is not defined
    at new CellLabels (eval at <anonymous> (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/sandboxManager.js:63:4), <anonymous>:127:15)
    at scrape (eval at <anonymous> (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/sandboxManager.js:63:4), <anonymous>:79:15)
    at doWeb (eval at <anonymous> (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/sandboxManager.js:63:4), <anonymous>:73:9)
    at Zotero.Translate.Web.rest (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/translate/translation/translate.js:1340:49)
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/translate/translation/translate.js:1325:39
url => https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A
downloadAssociatedFiles => true
automaticSnapshots => true
```

**Comment by jiaojiaodubai** [comment]
使用茉莉花更新到最新版后，尝试抓取未能复现你提到的问题。
![image](https://github.com/l0o0/translators_CN/assets/63148861/7b7dd093-ce98-4e92-95ec-3e028e46756f)

**Comment by doubanchan** [comment]
**补充**
在[[全文](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=7FA63E9BBA56E60471AEDAEBDE44B14C)]页可以正常抓取。搜索“ReferenceError”，好像其他插件出现过类似错误。

**Comment by jiaojiaodubai** [comment]
> **补充** 在[[全文](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=7FA63E9BBA56E60471AEDAEBDE44B14C)]页可以正常抓取。

难道多条目页面就不行吗？我这边没问题。
![image](https://github.com/l0o0/translators_CN/assets/63148861/17b296e4-963c-467e-ac76-abf300264fdc)

> 搜索“ReferenceError”，好像其他插件出现过类似错误。

其它转换器有问题再另外列出吧，这个issue我先关闭了？

**Comment by doubanchan** [comment]
好，你关了吧，可能不是translator的问题。
