### ISSUE TITLE
无法抓取知网学术论文条目信息

### ISSUE THREAD

**Issue by Code-Newborn** [l0o0/translators_CN#322]
**你遇到了什么问题？** [必填]
- [X] 无法识别条目
- [X] 无法保存条目
- [ ] 无法下载附件
- [ ] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
[CNKI_波束偏转超表面天线的研究与设计](https://kns.cnki.net/kcms2/article/abstract?v=w1Je9LIFm5CtSBZxBA0_V4MnRef471aVTH4SI3rNAQK135odaZqxCPrkITXNG99ta2Eh3Tw9hG1bDXhEdukXg5Iizs8BJEaY76dKghwngaDYFRMWxAktGYDWSYpOC__LIW-RoTnx9M1KbhJlbVzT6IIkOxpHkBs_EFtRSMT-JAE=&uniplatform=NZKPT&language=CHS)

**问题描述** [必填]
点击浏览器插件，试图将条目保存到zotero中，插件反应较慢。一段时间后插件出现信息栏，但识别文献状态呈现灰色，且无后续动作，zotero中无任何新添加记录。

**你的预期结果**
如：浏览器中的插件应该能够保存知网学术论文条目，前日使用还没有问题，更新过翻译器后貌似就不行了

**浏览器**

- [ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [x] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [X] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [X] 我尝试过重启浏览器、Zotero或电脑
- [X] 我使用VPN访问
- [X] 我使用校园网直接访问
- [ ] 我在海外访问

**附件**
如Connector报错记录（建议粘贴代码格式）：

```shell
[JavaScript Error: "Only 0 translators present in cache. Resetting
Error: Only 0 translators present in cache. Resetting
    at Object.init (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translators.js:87:20)
    at Object.update (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translators.js:281:47)
    at Object.update (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/repo.js:102:29)
    at async chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/repo.js:49:6"]

[JavaScript Error: "Missing property "translatorID" in translator metadata JSON object in undefined
Error: Missing property "translatorID" in translator metadata JSON object in undefined
    at Zotero.Translator.init (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:83:18)
    at new Zotero.Translator (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:73:7)
    at Object.postReceive (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messages.js:77:13)
    at chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messaging_inject.js:85:48" {file: "[object Object]"}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "Missing property "translatorID" in translator metadata JSON object in undefined
Error: Missing property "translatorID" in translator metadata JSON object in undefined
    at Zotero.Translator.init (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:83:18)
    at new Zotero.Translator (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:73:7)
    at Object.postReceive (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messages.js:77:13)
    at chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messaging_inject.js:85:48" {file: "[object Object]"}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "Missing property "translatorID" in translator metadata JSON object in undefined
Error: Missing property "translatorID" in translator metadata JSON object in undefined
    at Zotero.Translator.init (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:83:18)
    at new Zotero.Translator (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:73:7)
    at Object.postReceive (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messages.js:77:13)
    at chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messaging_inject.js:85:48" {file: "[object Object]"}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "Missing property "translatorID" in translator metadata JSON object in undefined
Error: Missing property "translatorID" in translator metadata JSON object in undefined
    at Zotero.Translator.init (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:83:18)
    at new Zotero.Translator (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translator.js:73:7)
    at Object.postReceive (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messages.js:77:13)
    at chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/messaging_inject.js:85:48" {file: "[object Object]"}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]
```

**Comment by jiaojiaodubai** [comment]
在Edge中未能复现， 请尝试通过重装Connector解决
![image](https://github.com/l0o0/translators_CN/assets/63148861/26465bd1-343a-4478-8a5d-77532eb929ee)

**Comment by Code-Newborn** [comment]
重启浏览器，即恢复正常了
