### ISSUE TITLE
Mac系统，cnki抓取知网学位论文需手动添加.caj后缀才能

### ISSUE THREAD

**Issue by Liuyulun** [l0o0/translators_CN#333]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [ ] 缺少字段、字段错误
- [ √] 其他

**发生问题的链接** [必填]
https://kns.cnki.net/kcms2/article/abstract?v=C06iYwc_NfRdvLJq5-_BO0FTEliRXPmDVfCrRmtT0ND12YG_6GTm3Wtuuhw3StJdmogV3yDmbscwKdvAqTsmgLM13tP3E6ZIHtUvTtfskdJZ2PMqgzle6CsW6nJX2FckDdtjVZSk84MMZzMWbi6hkjB7gyRJEFv9XTAVk9vn_0M=&uniplatform=NZKPT&language=CHS

**问题描述** [必填]
如：下载的文档缺失.caj后缀。

**你的预期结果**
如：不必手动添加，可直接打开。

**浏览器**

- [ √] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [√] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ √] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ √] 我使用校园网直接访问
- [ ] 我在海外访问

**附件**
如Connector报错记录（建议粘贴代码格式）：
![Connector的报错记录](https://picss.sunbangyan.cn/2023/12/05/428125effd2c72d84f558329b4dbcc36.jpeg)
![WechatIMG920](https://github.com/l0o0/translators_CN/assets/61680740/5ff9dafe-08da-4ee8-b2ea-19d408402f1b)
![WechatIMG921](https://github.com/l0o0/translators_CN/assets/61680740/14623ad1-4f0c-4050-970f-c9ec5e83e336)

```shell
[JavaScript Error: "No title specified for item
Error: No title specified for item
    at Object._itemDone (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translation/translate.js:609:32)
    at Object._itemDone (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/inject/sandboxManager.js:89:17)
    at Zotero.Item.complete (eval at <anonymous> (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/inject/sandboxManager.js:63:4), <anonymous>:1:306)
    at scrape (eval at <anonymous> (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/inject/sandboxManager.js:63:4), <anonymous>:353:12)
    at async doWeb (eval at <anonymous> (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/inject/sandboxManager.js:63:4), <anonymous>:215:4)" {file: "[object Object]"}]
```

**Comment by Liuyulun** [comment]
或者不用添加后缀，需要手动设置此类文档的默认打开方式，但是无法应用到所有此类文档，需要挨个设置。applaction/CAJ的调用失败。

**Comment by jiaojiaodubai** [comment]
如果你没有专门设置的话，当网站提供PDF附件的时候，转换器默认下载PDF格式的附件，我这边测试下载PDF正常。我使用Windows系统，mac的情况需要进一步调查。
![image](https://github.com/l0o0/translators_CN/assets/63148861/2d2f4e56-7914-4470-9440-e169fa575419)

**Comment by Liuyulun** [comment]
谢谢友友，PDF不太方便，我手动设置了每篇caj论文的打开程序。再次谢谢您！
















在 2024-04-02 15:11:12，"jiaojiaodubai" ***@***.***> 写道：

如果你没有专门设置的话，当网站提供PDF附件的时候，转换器默认下载PDF格式的附件，我这边测试下载PDF正常。我使用Windows系统，mac的情况需要进一步调查。
image.png (view on web)

**Comment by jiaojiaodubai** [comment]
> 谢谢友友，PDF不太方便

我不太理解CAJ方便在哪里，因为有目录可以看吗？

我测试了一下，Windows下，文件包含拓展名，因此可以被系统响应的阅读器识别出来。

![image](https://github.com/l0o0/translators_CN/assets/63148861/c0e34b13-5561-44f2-b8ff-a160448f3784)

**Comment by jiaojiaodubai** [comment]
关联 #333
如果这是一个可以被稳定复现的问题，那很有可能与translator无关，因为translator本身不依赖于具体平台。

**Comment by Liuyulun** [comment]
对，需要通过目录对整个论文有一个快速了解。我也倾向于可能是系统原因，我使用了最新的CAJViewer 9.0，不清楚是不是这个原因。
















在 2024-04-02 16:38:04，"jiaojiaodubai" ***@***.***> 写道：

关联 #333
如果这是一个可以被稳定复现的问题，那很有可能与translator无关，因为translator本身不依赖于具体平台。

**Comment by jiaojiaodubai** [comment]
> 需要通过目录对整个论文有一个快速了解。

茉莉花可以通过配置PDFtk来实现自动为学位论文的PDF添加目录，具体使用方法可自行搜索。PDF是更通用的格式，建议下载PDF。

> 最新的CAJViewer 9.0。

我个人使用[稻壳阅读器](https://www.daokeyuedu.com/)来查看CAJ文档，个人认为它更简洁易用。

**Comment by jiaojiaodubai** [comment]
可以复现，但 Translator 范围内无法处理，需要 Connector 的支持，但如何让 Connector 的开发人员获得可下载 CAJ 的测试环境是个问题。
