### ISSUE TITLE
无法下载万方PDF文档，日志报错找不到 translator

### ISSUE THREAD

**Issue by RikkaBlue** [l0o0/translators_CN#76]
事先在扩展更新了transators，

<details>
<summary>日志</summary>

```
(3)(+0004174): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000018): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1647177568927

(3)(+0000005): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000008): Translators: Saved updated translator list (695 translators)

(3)(+0000007): Repo: Next check in 86402s
```
</details>

---
但是在万方[单独条目](https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D)的浏览页刷新时，有提示：
```log
3)(+0000001): Not injecting. No translators found for [tab.url, url]: https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D , https://w.wanfangdata.com.cn/export.html
```

```log
(5)(+0000001): Translate: Running handler 0 for translators
```

完整日志：
<details>
<summary>展开</summary>

```
(3)(+0004275): Connector_Browser: onActivated for https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0001673): HTTP GET chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/utilities/resource/dateFormats.json

(3)(+0000977): Connector_Browser: onFrameLoaded for https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D; https://w.wanfangdata.com.cn/export.html

(3)(+0000000): Translators: Looking for translators for https://w.wanfangdata.com.cn/export.html

(3)(+0000001): Not injecting. No translators found for [tab.url, url]: https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D , https://w.wanfangdata.com.cn/export.html

(3)(+0001120): Translators: Looking for translators for https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000039): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000002): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000011): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000004): Connector: Method getTranslatorCode succeeded

(3)(+0000001): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000004): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000005): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000005): Connector: Method getTranslatorCode succeeded

(3)(+0000003): Connector: Method getTranslatorCode succeeded

(4)(+0000017): Translate: Binding sandbox to https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(4)(+0000012): Translate: Parsing code for Wanfang Data (eb876bd2-644c-458e-8d05-bf54b10176f3, 2021-07-18 12:07:54)

(3)(+0000004): {
    "dbname": "journalArticle"
    "filename": "ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D"
    "url": "https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D"
}

(4)(+0000004): Translate: Parsing code for Library Catalog (Visual Library 2021) (d23f01f1-6037-439b-87fb-23b8f3b9067f, 2021-07-19 16:39:31)

(4)(+0000004): Translate: Parsing code for unAPI (e7e01cac-1e37-4da6-b078-a0e8343b0e98, 2019-06-10 23:11:21)

(4)(+0000003): Translate: Parsing code for COinS (05d07af9-105a-4572-99f6-a8e231c0daef, 2021-06-01 17:38:46)

(4)(+0000005): Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2022-01-03 17:00:00)

(3)(+0000004): Translate: Embedded Metadata: found 7 meta tags.

(4)(+0000002): Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2020-03-13 02:38:54)

(3)(+0000005): Translate: All translator detect calls and RPC calls complete:

(3)(+0000000): 	Wanfang Data: 100

(3)(+0000000): 	DOI: 400

(5)(+0000001): Translate: Running handler 0 for translators

(3)(+0001020): translate message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/ping

(3)(+0000006): Connector: Method ping succeeded

(4)(+0000002): Translate: Binding sandbox to https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000001): progressWindow.show message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(4)(+0000010): Translate: Parsing code for Wanfang Data (eb876bd2-644c-458e-8d05-bf54b10176f3, 2021-07-18 12:07:54)

(3)(+0000000): Translate: Beginning translation with Wanfang Data

(3)(+0000001): {
    "dbname": "journalArticle"
    "filename": "ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D"
    "url": "https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D"
}

(3)(+0000001): Translate: ---------------WanFang Data 20210401---------------

(3)(+0000000): debug: level must be an integer

(3)(+0000000): Translate: resolving URL https://d.wanfangdata.com.cn/Detail/Periodical/

(3)(+0000001): Translate: resolved to https://d.wanfangdata.com.cn/Detail/Periodical/

(3)(+0000000): Zotero.HTTP.doPost is deprecated. Use Zotero.HTTP.request

(3)(+0000000): HTTP POST https://d.wanfangdata.com.cn/Detail/Periodical/

(3)(+0000050): progressWindowIframe.registered message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000003): HTTP POST http://127.0.0.1:23119/connector/getSelectedCollection

(3)(+0000002): progressWindowIframe.shown message received in injected page chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/progressWindow/progressWindow.html

(3)(+0000008): Connector: Method getSelectedCollection succeeded

(3)(+0000009): progressWindowIframe.changeHeadline message received in injected page chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/progressWindow/progressWindow.html

(3)(+0000010): progressWindowIframe.resized message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000022): Translate: Saving item

(5)(+0000001): Translate: Running handler 0 for itemSaving

(3)(+0000001): Translate: Saving via queue

(3)(+0000001): progressWindow.itemProgress message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000001): HTTP POST http://127.0.0.1:23119/connector/saveItems

(3)(+0000002): progressWindowIframe.updateProgress message received in injected page chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/progressWindow/progressWindow.html

(3)(+0000006): progressWindowIframe.resized message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000312): Connector: Method saveItems succeeded

(3)(+0000003): Translate: Save via Zotero succeeded

(5)(+0000001): Translate: Running handler 0 for itemDone

(3)(+0000001): HTTP POST http://127.0.0.1:23119/connector/sessionProgress

(5)(+0000001): Translate: Running handler 0 for done

(3)(+0000002): progressWindow.sessionCreated message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000001): progressWindow.itemProgress message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000001): progressWindow.done message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000002): progressWindowIframe.updateProgress message received in injected page chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/progressWindow/progressWindow.html

(3)(+0000003): Connector: Method sessionProgress succeeded

(3)(+0000238): progressWindowIframe.mouseenter message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000252): progressWindowIframe.mouseleave message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000339): Connector_Browser: onActivated for https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

(3)(+0000373): HTTP POST http://127.0.0.1:23119/connector/sessionProgress

(3)(+0000006): Connector: Method sessionProgress succeeded

(3)(+0000002): progressWindow.done message received in injected page https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEhBzeWpzeWdsMjAxNTExMDQyGggxY2JrOWoxNA%3D%3D

(3)(+0000511): Connector_Browser: onActivated for chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/preferences/preferences.html#advanced

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/ping

(3)(+0000007): Connector: Method ping succeeded
```
</details>

---
翻译器是下载仓库最新的版本，Zotero 是 5.0.96.3，浏览器 Chrome99

**Comment by RikkaBlue** [comment]
`Zotero.HTTP.doPost is deprecated. Use Zotero.HTTP.request` 是这个原因吗

**Comment by RikkaBlue** [comment]
```javascript
[JavaScript Error: "Error: Only 0 translators present in cache. Resetting
    at Object.init (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/translators.js:85:20)
    at Object.update (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/translators.js:264:47)
    at Object.update (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/repo.js:102:29)
    at async chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/repo.js:49:6"]

[JavaScript Error: "TypeError: Cannot read properties of undefined (reading '300')
    at Object.injectScripts (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:327:45)
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:266:36"]

[JavaScript Error: "TypeError: Cannot read properties of undefined (reading '324')
    at Object.injectScripts (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:327:45)
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:266:36"]

[JavaScript Error: "TypeError: Cannot read properties of undefined (reading '352')
    at Object.injectScripts (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:327:45)
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:266:36"]

[JavaScript Error: "TypeError: Cannot read properties of undefined (reading '806')
    at Object.injectScripts (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:327:45)
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:266:36"]

[JavaScript Error: "TypeError: Cannot read properties of undefined (reading '904')
    at Object.injectScripts (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:327:45)
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:266:36"]

[JavaScript Error: "Error: Inject: Tab removed mid-injection into 931 - https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjIwMzAyEg95c3NseWoyMDIxMDYzOTcaCDVqYm84Y3V1
    at tabRemovedListener (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/background.js:337:20)"]
```

**Comment by l0o0** [comment]
万方的之前的接口无效了，新接口的数据貌似加密了。可以用笨办法手动抓取html元素

**Comment by RikkaBlue** [comment]
非常感谢。
